services:
  - type: web
    name: esms-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_SERVER
        value: https://esms-backend.onrender.com/api
      - key: VITE_FILE_BASE_URL
        value: https://esms-backend.onrender.com/
      - key: PROD
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
